# Generated by Django 3.0.7 on 2020-06-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_change', models.DateField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(max_length=10)),
                ('phone_mob', models.TextField(max_length=10)),
                ('birth_date', models.DateTimeField()),
            ],
        ),
    ]
