# Generated by Django 3.0.7 on 2020-06-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_last_change',
            field=models.DateField(auto_now=True),
        ),
    ]
